name: Filter RSS Feed + Email

on:
  schedule:
    # 휴스턴 시간 오전 8시(CDT)에 실행 -> UTC 기준 13시
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  filter-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python with caching
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to filter RSS and create files
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python filter_rss_v3_NatSci.py
      
      - name: Upload email body file for next step
        uses: actions/upload-artifact@v4
        with:
          name: email-body
          path: filtered_titles.txt
          
      - name: Download email body file
        uses: actions/download-artifact@v4
        with:
          name: email-body
          
      - name: Send email with results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '[NatSci RSS] New Paper Updates'
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          body: file://filtered_titles.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
